### ISSUE TITLE
Can't extract /system/app/PrebuiltGmail/oat/arm64/PrebuiltGmail.vdex in Android 8.1, LGE Nexus 5X

### ISSUE THREAD

**Issue by Lonelyxin** [anestisb/vdexExtractor#12]
In LGE Nexus 5X, Android 8.1, the system app Gmail (path: /system/app/PrebuiltGmail/oat/arm64/PrebuiltGmail.vdex),  can not be extracted. 
error info:
[ERROR] Unexpected checksum (905cd253 vs b2a857d4) - failed to unquicken Dex file
[ERROR] Failed to process Dex files - skipping 'PrebuiltGmail.vdex'

**Comment by Lonelyxin** [comment]
Gmail file zip as below.

[PrebuiltGmail.zip](https://github.com/anestisb/vdexExtractor/files/1950560/PrebuiltGmail.zip)

**Comment by ale8530** [comment]
You have try use option --ignore-crc-error?

**Comment by anestisb** [comment]
@Lonelyxin check https://github.com/anestisb/vdexExtractor/issues/3 for more information on why you noticed this error in some apps

**Comment by Lonelyxin** [comment]
@anestisb @ale8530  Thanks !
use option --ignore-crc-error, vdex can be extracted. And the smali file is correct.
Thanks a lot!
