### ISSUE TITLE
after deodex is lags

### ISSUE THREAD

**Issue by levanhau03** [anestisb/vdexExtractor#15]
device : xiaomi redmi note 5 (pro )
after deodexed is lags
android 8.1
please fix it , thanks

**Comment by ale8530** [comment]
It's not a deodex problem, use the superr xda tool to fix the problem

**Comment by mwilky** [comment]
yup not an issue with the tool, what would be helpful though is if we could go the other way and turn the compiled dex back to vdex after doing our modifications?

**Comment by anestisb** [comment]
Τhis issue report does not make any sense at all. Btw if you want to optimize any DEX file, just pass it again to dex2oat compiler.
