### ISSUE TITLE
the latest source don't support android 9.0 vdex parse ???

### ISSUE THREAD

**Issue by LiuchengGit** [anestisb/vdexExtractor#19]
@anestisb,when i download your latest code and compile a vdexExtractor tool , i parse android P vdex ,get result as below . Doesn't  your code support Android 9.0 ???

root@book-virtual-machine:/work/vdexExtractor-master/bin# ./vdexExtractor -i tmp/boot-framework.vdex -o tmp --deps -f
[INFO] Processing 1 file(s) from tmp/boot-framework.vdex
[ERROR] Unsupported Vdex version
[WARNING] Invalid Vdex header - skipping 'tmp/boot-framework.vdex'
[INFO] 0 out of 0 Vdex files have been processed
[INFO] 0 Dex files have been extracted in total
[INFO] Extracted Dex files are available in 'tmp'

**Comment by anestisb** [comment]
Yeah Android 9.0 is not supported yet (see https://github.com/anestisb/vdexExtractor/issues/11). It's on the todo list, although I've been busy lately so limited free to time.
