### ISSUE TITLE
Strategy to convert CompactDex back to StandardDex

### ISSUE THREAD

**Issue by anestisb** [anestisb/vdexExtractor#23]
When the Vdex 019 unquicken decompiler is completed (some minor bugs left to be fixed), need to figure out a way to convert CompactDex back to StandardDex. This is required since most tools (e.g. JEB2) and AOSP build infra (see [android-prepare-vendor](https://github.com/anestisb/android-prepare-vendor) requirements) does not support CompactDex. And most likely they never will since CompactDex is considered an ART internal file.

Some possible approaches are:
* Use libdexlayout from ART
* Try to manually convert CompactDex without implementing a layout IR
* Fork the Dex layout IR from libart and wrap-around a conversion API

All 3 approaches require a significant deal of code reading and testing, with the optimal candidate being the first for the time being. So this might take some time.

**Comment by Surge1223** [comment]
I'm not sure if this might help, but I was exploring option 1 as well, I was reading code and came across this https://android.googlesource.com/platform/art/+/master/openjdkjvmti/fixed_up_dex_file.cc#113  since it has to return standard dex, and the library itself depends on libdexlayout I thought it might be useful for this goal.

**Comment by anestisb** [comment]
@Surge1223 I've seen it and already used similar code in an initial patch I tried for the oatdump tool (check it [here](https://gist.github.com/anestisb/26ecf8ae13746dc476eddd8d04a5dd23)). Unfortunately it's not very stable (memory OOB issues when processing Vdex files without an ART runtime - aka from a host binary) for reasons I cannot figure out yet. And for the files that it worked, the checksums & file sizes were not matching the original Dex files (garbage 4bytes padding per Dex + shifted data offsets).

I'm currently reading how dexlayout work, and initial evidence indicate that a fully reverted Dex that matches the initial bytecode checksum will not be possible. However, it seems that supporting CompactDex and exporting a functionally identical StandardDex is possible. Will keep the thread updated, in case more people want to contribute.

**Comment by anestisb** [comment]
I've finished an initial prototype of a new standalone ART utility to convert the CompactDex files back to StandardDex. It is available [here](https://gist.github.com/anestisb/30265097ad9a5ea2f0ddf7e36db3f07d). It manually opens input CompactDex files with the DexFileLoader primitive, instead of the ArtDexFileLoader which supports opening only from Vdex containers. Then for each file, libdexlayout is used to process data collections, create IR and generate the standard DexContainers. The main section of the DexContainer is then exported (and optionally verified) to the output directory.

I've tested the tool against a series of vdexExtractor decompiled Android P files I've gathered and so far it works without any major issues being spotted. For each converted DexFile I've also used the dexdump2 utility to verify that the ART dex parsers are happy & can verify the converted file.

It should be noted though that after manually examining a small set of converted Dex files, they're not matching 100% to the original file. Some offsets have been shuffled (e.g. class_data offsets swaped with matching class_annotation offsets), although the Dex files appear to be functionally identical (bytecode verified by diff-ing dexdump2 output against original Dex).

I'll do some more testing and then decide what is the optimal way to distribute the converter tool. Most probably would do something similar to android-prepare vendor, which is compile the baseline libs for Linux & macOS, distribute via a file sharing URL and wrap-around automation via a bash script.

Ideally I would like to create a standalone version of the libdexlayout so I can use it independently of AOSP builds, although handling all the ART lib dependencies atm is very tight due to limited timeframes.

The final step is to raise an issue in the Android tracker and chat with the ART devs on the preferred path to upstream the conversion logic. It would be extremely painful to independently maintain this tool while ART involves. It is very likely that an Android 9.1 will drop with the Pixel 3 release, although hopefully it will get merged in the Android 10 release.

```
$ vdexExtractor/bin/vdexExtractor -i 019_vdex -o cdex_tmp -f && find cdex_tmp -type f | while read -r file; do /fast-datavault/aosp_prod/out_userdebug_release_Linux_9.0.0_r2/aosp_prod/host/linux-x86/bin/compact_dex_converter -w converted_tmp $file && /fast-datavault/aosp_prod/out_userdebug_release_Linux_9.0.0_r2/aosp_prod/host/linux-x86/bin/dexdump2 -a -d -f -h -o converted_tmp/$(basename "$file").dump converted_tmp/$(basename "$file"); done
[INFO] 151 input files have been added to the list
[INFO] Processing 151 file(s) from 019_vdex
[INFO] 151 out of 151 Vdex files have been processed
[INFO] 77 Dex files have been extracted in total
[INFO] Extracted Dex files are available in 'cdex_tmp'
Opened 'cdex_tmp/BluetoothMidiService.apk_classes.cdex', DEX version '001'
compact_dex_converter I 09-02 11:27:43  1706  1706 compact_dex_converter_main.cc:172] StandardDex file successfully extracted to converted_tmp/BluetoothMidiService.apk_classes.cdex
Opened 'cdex_tmp/CloudPrint2.apk_classes.cdex', DEX version '001'
compact_dex_converter I 09-02 11:27:44  1710  1710 compact_dex_converter_main.cc:172] StandardDex file successfully extracted to converted_tmp/CloudPrint2.apk_classes.cdex
Opened 'cdex_tmp/PrebuiltDeskClockGoogle.apk_classes.cdex', DEX version '001'
compact_dex_converter I 09-02 11:27:44  1714  1714 compact_dex_converter_main.cc:172] StandardDex file successfully extracted to converted_tmp/PrebuiltDeskClockGoogle.apk_classes.cdex
Opened 'cdex_tmp/Ornament.apk_classes.cdex', DEX version '001'
compact_dex_converter I 09-02 11:27:45  1718  1718 compact_dex_converter_main.cc:172] StandardDex file successfully extracted to converted_tmp/Ornament.apk_classes.cdex
Opened 'cdex_tmp/HTMLViewer.apk_classes.cdex', DEX version '001'
compact_dex_converter I 09-02 11:27:45  1722  1722 compact_dex_converter_main.cc:172] StandardDex file successfully extracted to converted_tmp/HTMLViewer.apk_classes.cdex
Opened 'cdex_tmp/NexusWallpapersStubPrebuilt.apk_classes.cdex', DEX version '001'
compact_dex_converter I 09-02 11:27:45  1726  1726 compact_dex_converter_main.cc:172] StandardDex file successfully extracted to converted_tmp/NexusWallpapersStubPrebuilt.apk_classes.cdex
Opened 'cdex_tmp/Photos.apk_classes.cdex', DEX version '001'
compact_dex_converter I 09-02 11:27:45  1730  1730 compact_dex_converter_main.cc:172] StandardDex file successfully extracted to converted_tmp/Photos.apk_classes.cdex
Opened 'cdex_tmp/SafetyRegulatoryInfo.apk_classes.cdex', DEX version '001'
compact_dex_converter I 09-02 11:27:48  1734  1734 compact_dex_converter_main.cc:172] StandardDex file successfully extracted to converted_tmp/SafetyRegulatoryInfo.apk_classes.cdex
Opened 'cdex_tmp/DMAgent.apk_classes.cdex', DEX version '001'
compact_dex_converter I 09-02 11:27:48  1738  1738 compact_dex_converter_main.cc:172] StandardDex file successfully extracted to converted_tmp/DMAgent.apk_classes.cdex
Opened 'cdex_tmp/PrebuiltBugle.apk_classes3.cdex', DEX version '001'
compact_dex_converter I 09-02 11:27:49  1742  1742 compact_dex_converter_main.cc:172] StandardDex file successfully extracted to converted_tmp/PrebuiltBugle.apk_classes3.cdex
Opened 'cdex_tmp/YouTube.apk_classes3.cdex', DEX version '001'
compact_dex_converter I 09-02 11:27:49  1746  1746 compact_dex_converter_main.cc:172] StandardDex file successfully extracted to converted_tmp/YouTube.apk_classes3.cdex
Opened 'cdex_tmp/CertInstaller.apk_classes.cdex', DEX version '001'
compact_dex_converter I 09-02 11:27:50  1750  1750 compact_dex_converter_main.cc:172] StandardDex file successfully extracted to converted_tmp/CertInstaller.apk_classes.cdex
Opened 'cdex_tmp/WebViewStub.apk_classes.cdex', DEX version '001'
compact_dex_converter I 09-02 11:27:50  1754  1754 compact_dex_converter_main.cc:172] StandardDex file successfully extracted to converted_tmp/WebViewStub.apk_classes.cdex
Opened 'cdex_tmp/Maps.apk_classes2.cdex', DEX version '001'
compact_dex_converter I 09-02 11:27:50  1758  1758 compact_dex_converter_main.cc:172] StandardDex file successfully extracted to converted_tmp/Maps.apk_classes2.cdex
Opened 'cdex_tmp/StickersMusic.apk_classes.cdex', DEX version '001'
compact_dex_converter I 09-02 11:27:53  1762  1762 compact_dex_converter_main.cc:172] StandardDex file successfully extracted to converted_tmp/StickersMusic.apk_classes.cdex
Opened 'cdex_tmp/BuiltInPrintService.apk_classes.cdex', DEX version '001'
compact_dex_converter I 09-02 11:27:54  1766  1766 compact_dex_converter_main.cc:172] StandardDex file successfully extracted to converted_tmp/BuiltInPrintService.apk_classes.cdex
Opened 'cdex_tmp/Drive.apk_classes2.cdex', DEX version '001'
compact_dex_converter I 09-02 11:27:54  1770  1770 compact_dex_converter_main.cc:172] StandardDex file successfully extracted to converted_tmp/Drive.apk_classes2.cdex
Opened 'cdex_tmp/BookmarkProvider.apk_classes.cdex', DEX version '001'
compact_dex_converter I 09-02 11:27:54  1774  1774 compact_dex_converter_main.cc:172] StandardDex file successfully extracted to converted_tmp/BookmarkProvider.apk_classes.cdex
Opened 'cdex_tmp/PrebuiltGmail.apk_classes.cdex', DEX version '001'
compact_dex_converter I 09-02 11:27:54  1778  1778 compact_dex_converter_main.cc:172] StandardDex file successfully extracted to converted_tmp/PrebuiltGmail.apk_classes.cdex
Opened 'cdex_tmp/CaptivePortalLogin.apk_classes.cdex', DEX version '001'
compact_dex_converter I 09-02 11:27:57  1782  1782 compact_dex_converter_main.cc:172] StandardDex file successfully extracted to converted_tmp/CaptivePortalLogin.apk_classes.cdex
Opened 'cdex_tmp/Maps.apk_classes3.cdex', DEX version '001'
compact_dex_converter I 09-02 11:27:57  1786  1786 compact_dex_converter_main.cc:172] StandardDex file successfully extracted to converted_tmp/Maps.apk_classes3.cdex
Opened 'cdex_tmp/PlayAutoInstallConfig.apk_classes.cdex', DEX version '001'
compact_dex_converter I 09-02 11:28:00  1790  1790 compact_dex_converter_main.cc:172] StandardDex file successfully extracted to converted_tmp/PlayAutoInstallConfig.apk_classes.cdex
Opened 'cdex_tmp/GoogleTTS.apk_classes.cdex', DEX version '001'
compact_dex_converter I 09-02 11:28:00  1794  1794 compact_dex_converter_main.cc:172] StandardDex file successfully extracted to converted_tmp/GoogleTTS.apk_classes.cdex
Opened 'cdex_tmp/Maps.apk_classes.cdex', DEX version '001'
compact_dex_converter I 09-02 11:28:01  1798  1798 compact_dex_converter_main.cc:172] StandardDex file successfully extracted to converted_tmp/Maps.apk_classes.cdex
Opened 'cdex_tmp/GoogleContactsSyncAdapter.apk_classes.cdex', DEX version '001'
compact_dex_converter I 09-02 11:28:03  1802  1802 compact_dex_converter_main.cc:172] StandardDex file successfully extracted to converted_tmp/GoogleContactsSyncAdapter.apk_classes.cdex
Opened 'cdex_tmp/CompanionDeviceManager.apk_classes.cdex', DEX version '001'
compact_dex_converter I 09-02 11:28:04  1806  1806 compact_dex_converter_main.cc:172] StandardDex file successfully extracted to converted_tmp/CompanionDeviceManager.apk_classes.cdex
Opened 'cdex_tmp/GoogleCamera.apk_classes.cdex', DEX version '001'
compact_dex_converter I 09-02 11:28:04  1810  1810 compact_dex_converter_main.cc:172] StandardDex file successfully extracted to converted_tmp/GoogleCamera.apk_classes.cdex
Opened 'cdex_tmp/PrebuiltBugle.apk_classes4.cdex', DEX version '001'
compact_dex_converter I 09-02 11:28:06  1814  1814 compact_dex_converter_main.cc:172] StandardDex file successfully extracted to converted_tmp/PrebuiltBugle.apk_classes4.cdex
Opened 'cdex_tmp/BasicDreams.apk_classes.cdex', DEX version '001'
compact_dex_converter I 09-02 11:28:07  1818  1818 compact_dex_converter_main.cc:172] StandardDex file successfully extracted to converted_tmp/BasicDreams.apk_classes.cdex
Opened 'cdex_tmp/Bluetooth.apk_classes.cdex', DEX version '001'
compact_dex_converter I 09-02 11:28:08  1822  1822 compact_dex_converter_main.cc:172] StandardDex file successfully extracted to converted_tmp/Bluetooth.apk_classes.cdex
Opened 'cdex_tmp/CalculatorGooglePrebuilt.apk_classes.cdex', DEX version '001'
compact_dex_converter I 09-02 11:28:09  1826  1826 compact_dex_converter_main.cc:172] StandardDex file successfully extracted to converted_tmp/CalculatorGooglePrebuilt.apk_classes.cdex
Opened 'cdex_tmp/Drive.apk_classes.cdex', DEX version '001'
compact_dex_converter I 09-02 11:28:09  1830  1830 compact_dex_converter_main.cc:172] StandardDex file successfully extracted to converted_tmp/Drive.apk_classes.cdex
Opened 'cdex_tmp/Music2.apk_classes.cdex', DEX version '001'
compact_dex_converter I 09-02 11:28:12  1834  1834 compact_dex_converter_main.cc:172] StandardDex file successfully extracted to converted_tmp/Music2.apk_classes.cdex
Opened 'cdex_tmp/FaceLock.apk_classes.cdex', DEX version '001'
compact_dex_converter I 09-02 11:28:14  1838  1838 compact_dex_converter_main.cc:172] StandardDex file successfully extracted to converted_tmp/FaceLock.apk_classes.cdex
Opened 'cdex_tmp/Videos.apk_classes2.cdex', DEX version '001'
compact_dex_converter I 09-02 11:28:14  1842  1842 compact_dex_converter_main.cc:172] StandardDex file successfully extracted to converted_tmp/Videos.apk_classes2.cdex
Opened 'cdex_tmp/LiveWallpapersPicker.apk_classes.cdex', DEX version '001'
compact_dex_converter I 09-02 11:28:15  1846  1846 compact_dex_converter_main.cc:172] StandardDex file successfully extracted to converted_tmp/LiveWallpapersPicker.apk_classes.cdex
Opened 'cdex_tmp/YouTube.apk_classes.cdex', DEX version '001'
compact_dex_converter I 09-02 11:28:15  1850  1850 compact_dex_converter_main.cc:172] StandardDex file successfully extracted to converted_tmp/YouTube.apk_classes.cdex
Opened 'cdex_tmp/Maps.apk_classes4.cdex', DEX version '001'
compact_dex_converter I 09-02 11:28:20  1854  1854 compact_dex_converter_main.cc:172] StandardDex file successfully extracted to converted_tmp/Maps.apk_classes4.cdex
Opened 'cdex_tmp/StickersSports.apk_classes.cdex', DEX version '001'
compact_dex_converter I 09-02 11:28:22  1858  1858 compact_dex_converter_main.cc:172] StandardDex file successfully extracted to converted_tmp/StickersSports.apk_classes.cdex
Opened 'cdex_tmp/GooglePrintRecommendationService.apk_classes.cdex', DEX version '001'
compact_dex_converter I 09-02 11:28:22  1862  1862 compact_dex_converter_main.cc:172] StandardDex file successfully extracted to converted_tmp/GooglePrintRecommendationService.apk_classes.cdex
Opened 'cdex_tmp/SecureElement.apk_classes.cdex', DEX version '001'
compact_dex_converter I 09-02 11:28:22  1866  1866 compact_dex_converter_main.cc:172] StandardDex file successfully extracted to converted_tmp/SecureElement.apk_classes.cdex
Opened 'cdex_tmp/LatinIMEGooglePrebuilt.apk_classes.cdex', DEX version '001'
compact_dex_converter I 09-02 11:28:22  1870  1870 compact_dex_converter_main.cc:172] StandardDex file successfully extracted to converted_tmp/LatinIMEGooglePrebuilt.apk_classes.cdex
Opened 'cdex_tmp/YouTube.apk_classes2.cdex', DEX version '001'
compact_dex_converter I 09-02 11:28:24  1874  1874 compact_dex_converter_main.cc:172] StandardDex file successfully extracted to converted_tmp/YouTube.apk_classes2.cdex
Opened 'cdex_tmp/Photos.apk_classes2.cdex', DEX version '001'
compact_dex_converter I 09-02 11:28:26  1878  1878 compact_dex_converter_main.cc:172] StandardDex file successfully extracted to converted_tmp/Photos.apk_classes2.cdex
Opened 'cdex_tmp/MarkupGoogle.apk_classes.cdex', DEX version '001'
compact_dex_converter I 09-02 11:28:28  1882  1882 compact_dex_converter_main.cc:172] StandardDex file successfully extracted to converted_tmp/MarkupGoogle.apk_classes.cdex
Opened 'cdex_tmp/Traceur.apk_classes.cdex', DEX version '001'
compact_dex_converter I 09-02 11:28:29  1886  1886 compact_dex_converter_main.cc:172] StandardDex file successfully extracted to converted_tmp/Traceur.apk_classes.cdex
Opened 'cdex_tmp/RcsService.apk_classes.cdex', DEX version '001'
compact_dex_converter I 09-02 11:28:29  1890  1890 compact_dex_converter_main.cc:172] StandardDex file successfully extracted to converted_tmp/RcsService.apk_classes.cdex
Opened 'cdex_tmp/WallpapersUsTwo.apk_classes.cdex', DEX version '001'
compact_dex_converter I 09-02 11:28:29  1894  1894 compact_dex_converter_main.cc:172] StandardDex file successfully extracted to converted_tmp/WallpapersUsTwo.apk_classes.cdex
Opened 'cdex_tmp/SimAppDialog.apk_classes.cdex', DEX version '001'
compact_dex_converter I 09-02 11:28:30  1898  1898 compact_dex_converter_main.cc:172] StandardDex file successfully extracted to converted_tmp/SimAppDialog.apk_classes.cdex
Opened 'cdex_tmp/WallpapersBReel.apk_classes.cdex', DEX version '001'
compact_dex_converter I 09-02 11:28:30  1902  1902 compact_dex_converter_main.cc:172] StandardDex file successfully extracted to converted_tmp/WallpapersBReel.apk_classes.cdex
Opened 'cdex_tmp/PrebuiltBugle.apk_classes.cdex', DEX version '001'
compact_dex_converter I 09-02 11:28:31  1906  1906 compact_dex_converter_main.cc:172] StandardDex file successfully extracted to converted_tmp/PrebuiltBugle.apk_classes.cdex
Opened 'cdex_tmp/HangoutsStub.apk_classes.cdex', DEX version '001'
compact_dex_converter I 09-02 11:28:33  1910  1910 compact_dex_converter_main.cc:172] StandardDex file successfully extracted to converted_tmp/HangoutsStub.apk_classes.cdex
Opened 'cdex_tmp/SoundPickerPrebuilt.apk_classes.cdex', DEX version '001'
compact_dex_converter I 09-02 11:28:33  1914  1914 compact_dex_converter_main.cc:172] StandardDex file successfully extracted to converted_tmp/SoundPickerPrebuilt.apk_classes.cdex
Opened 'cdex_tmp/PartnerBookmarksProvider.apk_classes.cdex', DEX version '001'
compact_dex_converter I 09-02 11:28:33  1918  1918 compact_dex_converter_main.cc:172] StandardDex file successfully extracted to converted_tmp/PartnerBookmarksProvider.apk_classes.cdex
Opened 'cdex_tmp/Music2.apk_classes2.cdex', DEX version '001'
compact_dex_converter I 09-02 11:28:33  1922  1922 compact_dex_converter_main.cc:172] StandardDex file successfully extracted to converted_tmp/Music2.apk_classes2.cdex
Opened 'cdex_tmp/Videos.apk_classes.cdex', DEX version '001'
compact_dex_converter I 09-02 11:28:35  1926  1926 compact_dex_converter_main.cc:172] StandardDex file successfully extracted to converted_tmp/Videos.apk_classes.cdex
Opened 'cdex_tmp/Photos.apk_classes3.cdex', DEX version '001'
compact_dex_converter I 09-02 11:28:37  1930  1930 compact_dex_converter_main.cc:172] StandardDex file successfully extracted to converted_tmp/Photos.apk_classes3.cdex
Opened 'cdex_tmp/ConnectivityMonitor.apk_classes.cdex', DEX version '001'
compact_dex_converter I 09-02 11:28:38  1934  1934 compact_dex_converter_main.cc:172] StandardDex file successfully extracted to converted_tmp/ConnectivityMonitor.apk_classes.cdex
Opened 'cdex_tmp/PacProcessor.apk_classes.cdex', DEX version '001'
compact_dex_converter I 09-02 11:28:38  1938  1938 compact_dex_converter_main.cc:172] StandardDex file successfully extracted to converted_tmp/PacProcessor.apk_classes.cdex
Opened 'cdex_tmp/Chrome.apk_classes.cdex', DEX version '001'
compact_dex_converter I 09-02 11:28:38  1942  1942 compact_dex_converter_main.cc:172] StandardDex file successfully extracted to converted_tmp/Chrome.apk_classes.cdex
Opened 'cdex_tmp/Tycho.apk_classes.cdex', DEX version '001'
compact_dex_converter I 09-02 11:28:40  1946  1946 compact_dex_converter_main.cc:172] StandardDex file successfully extracted to converted_tmp/Tycho.apk_classes.cdex
Opened 'cdex_tmp/GoogleVrCore.apk_classes.cdex', DEX version '001'
compact_dex_converter I 09-02 11:28:42  1950  1950 compact_dex_converter_main.cc:172] StandardDex file successfully extracted to converted_tmp/GoogleVrCore.apk_classes.cdex
Opened 'cdex_tmp/EasterEgg.apk_classes.cdex', DEX version '001'
compact_dex_converter I 09-02 11:28:42  1954  1954 compact_dex_converter_main.cc:172] StandardDex file successfully extracted to converted_tmp/EasterEgg.apk_classes.cdex
Opened 'cdex_tmp/SMSConnectPrebuilt.apk_classes.cdex', DEX version '001'
compact_dex_converter I 09-02 11:28:43  1958  1958 compact_dex_converter_main.cc:172] StandardDex file successfully extracted to converted_tmp/SMSConnectPrebuilt.apk_classes.cdex
Opened 'cdex_tmp/CarrierDefaultApp.apk_classes.cdex', DEX version '001'
compact_dex_converter I 09-02 11:28:43  1962  1962 compact_dex_converter_main.cc:172] StandardDex file successfully extracted to converted_tmp/CarrierDefaultApp.apk_classes.cdex
Opened 'cdex_tmp/arcore.apk_classes.cdex', DEX version '001'
compact_dex_converter I 09-02 11:28:44  1966  1966 compact_dex_converter_main.cc:172] StandardDex file successfully extracted to converted_tmp/arcore.apk_classes.cdex
Opened 'cdex_tmp/PrebuiltGmail.apk_classes2.cdex', DEX version '001'
compact_dex_converter I 09-02 11:28:44  1970  1970 compact_dex_converter_main.cc:172] StandardDex file successfully extracted to converted_tmp/PrebuiltGmail.apk_classes2.cdex
dexdump2 E 09-02 11:28:44  1973  1973 dexdump.cc:1907] Failure to verify dex file 'converted_tmp/PrebuiltGmail.apk_classes2.cdex': Invalid class definition ordering: class with type idx: '2153' defined before superclass with type idx: '7409'
Opened 'cdex_tmp/PresencePolling.apk_classes.cdex', DEX version '001'
compact_dex_converter I 09-02 11:28:44  1974  1974 compact_dex_converter_main.cc:172] StandardDex file successfully extracted to converted_tmp/PresencePolling.apk_classes.cdex
Opened 'cdex_tmp/PrebuiltBugle.apk_classes2.cdex', DEX version '001'
compact_dex_converter I 09-02 11:28:44  1978  1978 compact_dex_converter_main.cc:172] StandardDex file successfully extracted to converted_tmp/PrebuiltBugle.apk_classes2.cdex
Opened 'cdex_tmp/CarrierMetrics.apk_classes.cdex', DEX version '001'
compact_dex_converter I 09-02 11:28:44  1982  1982 compact_dex_converter_main.cc:172] StandardDex file successfully extracted to converted_tmp/CarrierMetrics.apk_classes.cdex
Opened 'cdex_tmp/GoogleContacts.apk_classes.cdex', DEX version '001'
compact_dex_converter I 09-02 11:28:45  1986  1986 compact_dex_converter_main.cc:172] StandardDex file successfully extracted to converted_tmp/GoogleContacts.apk_classes.cdex
Opened 'cdex_tmp/StickersJapan.apk_classes.cdex', DEX version '001'
compact_dex_converter I 09-02 11:28:46  1990  1990 compact_dex_converter_main.cc:172] StandardDex file successfully extracted to converted_tmp/StickersJapan.apk_classes.cdex
Opened 'cdex_tmp/CalendarGooglePrebuilt.apk_classes.cdex', DEX version '001'
compact_dex_converter I 09-02 11:28:46  1994  1994 compact_dex_converter_main.cc:172] StandardDex file successfully extracted to converted_tmp/CalendarGooglePrebuilt.apk_classes.cdex
Opened 'cdex_tmp/talkback.apk_classes.cdex', DEX version '001'
compact_dex_converter I 09-02 11:28:48  1998  1998 compact_dex_converter_main.cc:172] StandardDex file successfully extracted to converted_tmp/talkback.apk_classes.cdex
Opened 'cdex_tmp/GoogleExtShared.apk_classes.cdex', DEX version '001'
compact_dex_converter I 09-02 11:28:49  2002  2002 compact_dex_converter_main.cc:172] StandardDex file successfully extracted to converted_tmp/GoogleExtShared.apk_classes.cdex
Opened 'cdex_tmp/NfcNci.apk_classes.cdex', DEX version '001'
compact_dex_converter I 09-02 11:28:49  2006  2006 compact_dex_converter_main.cc:172] StandardDex file successfully extracted to converted_tmp/NfcNci.apk_classes.cdex
Opened 'cdex_tmp/PrintSpooler.apk_classes.cdex', DEX version '001'
compact_dex_converter I 09-02 11:28:50  2010  2010 compact_dex_converter_main.cc:172] StandardDex file successfully extracted to converted_tmp/PrintSpooler.apk_classes.cdex
```

**Comment by anestisb** [comment]
For those interested to experiment, a set of Linux binaries is available [here](https://1drv.ms/u/s!ArDC4mvMyPrRhEGTqd0AxKpJA0_h).

**Comment by Furniel** [comment]
How compact_dex_converter can be build for Windows? "make win_sdk" or Windows build not supported at this moment?

**Comment by anestisb** [comment]
@Furniel AOSP building in Windows is not currently supported from Google, so compiling the compact_dex_converter for the Windows host is not possible. An alternative would be to compile once on Linux/macOS and then run the arm binaries of the tool in Android devices to do the conversion on the devices/emulators.

I'm looking for DEX IR alternatives that can be built outside AOSP, although couldn't find something decent to work with. dexlib2 primitives are not flexible (plus hate to write Java), facebook redex is strongly coupled with optimization rounds so hard to isolate IR part, and the AOSP ART IR builder is strongly coupled with libart, base libs & Android build env, thus painful to standalonize.

Any further ideas are more than welcome.

**Comment by anestisb** [comment]
Fixed minor bugs & polished the compact_dex_converter tool (see gist revisions). New release & debug binaries uploaded for [Linux](https://1drv.ms/u/s!ArDC4mvMyPrRhEXEUdUS6Rl1f1Qz) and [macOS](https://1drv.ms/u/s!ArDC4mvMyPrRhESu8RFKIIVhe5fq).

**Comment by anestisb** [comment]
Wrap around scripting has been also pushed to master. You can use the deodex tool to automate the decompilation & conversion of the CompactDex files back to StandardDex.

Will keep the issue open for the time being in case more people want to jump-in with ideas about a usable Dex IR so I can get rid off the AOSP dependencies for the converter tool.

Unfortunately I don't have much more time to work on this project so this is probably as good as it can get for the time being.

**Comment by anestisb** [comment]
@Furniel nice. However, you don't need to remount the /data partition nor root access. You just need shell access to upload the cdex files and the compact_dex_converter executable, run it and download the output dex. Simply enabling ADB access should be more than enough.

**Comment by Furniel** [comment]
@anestisb We can't run binaries from /sdcard on android, so only solution i foud is to use /data partition, but we can't push or pull to data(or even view it) without root. Maybe i missed something?

**Comment by anestisb** [comment]
@Furniel "/data/local/tmp" should not be under sdcard even for devices that have one. shell user (from adb) should have access to read/write/execute files in that directory based on current DAC/MAC.

**Comment by superr** [comment]
Thank you @anestisb for the Linux and Mac binaries.
Thank you @Furniel for the static Linux binary.

Unfortunately, none of the Linux binaries work on my 64-bit Ubuntu 16.04.5 install.
```
$ ./compact_dex_converter services_classes.cdex 
Opened 'services_classes.cdex', DEX version '001'
Illegal instruction (core dumped)
```
The error is the same with static and shared libs. Any idea what might cause this? 
Thanks

**Comment by anestisb** [comment]
@superr can you run the build with the shared libraries under valgrind and paste the report? It would be great if you can do it on a separate issue so the problem can be tracked properly.

**Comment by superr** [comment]
Thank you for your response :) 

Here comes a glob of my ignorance... I am not familiar with valgrind, and I did not build the compact_dex_converter binaries. I used the ones you provided and the ones @Furniel provided, both with the same results. I did compile vdexExtractor and it is working perfectly.

**Comment by Furniel** [comment]
@superr 
Installed Ubuntu 16.04 on vbox and tested compact_dex_converter - everything works without issues. Are you sure that problem in compact_dex_converter, but not in cdex file?(I've got simillar issue with corrupted cdex file, which was genereted by old vdex extractor version).

**Comment by superr** [comment]
Thanks @Furniel. I am sure in this case.

1. I am using the latest vdexExtractor source
2. I sent the same file to another user and it converted without issue on their Ubuntu 16.04.

It seems something in my system does not like these binaries, but I am clueless. To be sure, I have attached the cdex file for testing. Thanks :)

[services_classes.cdex.zip](https://github.com/anestisb/vdexExtractor/files/2357825/services_classes.cdex.zip)

**Comment by anestisb** [comment]
@superr please open a new issue to track the problem you have with the distributed binaries.

valgrind is a dynamic instrumentation framework and can be used to debug applications. Just install it (`sudo apt-get install valgrind` for your Ubuntu) and run the converter via valgrind (`valgrind ./compact_dex_converterd <input_cdex>`). Then paste the report in the issue.

**Comment by ale8530** [comment]
@Furniel great work i have try your compact_dex_converter for linux and work perfect.

@anestisb is possible insert compile tool of @Furniel on your github?

**Comment by ale8530** [comment]
For those who need to load certain scripts on github deodex can not load all the hostTools folder, which is used to run the file compact_dex_converter, with the tool developed by @furniel I have the ability to load everything on github without libraries

**Comment by anestisb** [comment]
@ale8530 I see. I don't like sharing binaries over github thus the solution with the matching API-level wrapping over an external URL. If you modify the gitignore you should be ok sharing the files.

At any case I'll compile all targets and add URLs to the statically compiled binaries too in the README file in case someone wants them. Expect them later today.

**Comment by ale8530** [comment]
@anestisb Thanks for the great support you provide to the community, take it easy is not urgent :)

**Comment by cmstew** [comment]
I thought I'd share this with you guys. It's just another way to use anestisb's awesome tool if binaries aren't your thing:

http://vdex2dex.com/

**Comment by kevinminions9** [comment]
> 
> 
> Implemented android P deodexing under windows in [my tool](https://github.com/Furniel/Apk-Changer).
> 
> **Strategy to convert CompactDex back to StandardDex under windows(All versions)**:
> You need adb, any android device or emulator and compact_dex_converter tool
> Execute from cmd:
> 
> ```
> adb push compact_dex_converter /data/local/tmp/
> adb shell chmod 777 /data/local/tmp/bin/compact_dex_converter
> adb push your.cdex /data/local/tmp/classes.cdex
> adb shell "/data/local/tmp/compact_dex_converter /data/local/tmp/classes.cdex"
> adb pull /data/local/tmp/classes.cdex.new your.dex
> ```
> 
> Personally i recommend use android x86_64 emulator.
> 
> **Strategy to convert CompactDex back to StandardDex under Windows 10 x64**:
> Microsoft introduced WSL(Windows Subsystem for Linux) for windows 10, so windows 10 users can run compact_dex_converter linux binary under windows:
> 
>     1. Open control panel -> programs and features -> features and check if wsl is enabled
> 
>     2. Open windows store and install one of linux distributions(Ubuntu, CentOS, Kali and few others supported)
> 
>     3. Run installed distribution and wait until it will be configured, on last step you will be asked for user name and password
> 
>     4. Thats all, now you can run compact_dex_converter from wsl command promt
> 
> 
> Static compact_dex_converter binaries for linux and android:
> [compact_dex_converter_android_arm64-v8a.zip](https://github.com/anestisb/vdexExtractor/files/2351602/compact_dex_converter_android_arm64-v8a.zip)
> [compact_dex_converter_android_armeabi-v7a.zip](https://github.com/anestisb/vdexExtractor/files/2351603/compact_dex_converter_android_armeabi-v7a.zip)
> [compact_dex_converter_android_x86.zip](https://github.com/anestisb/vdexExtractor/files/2351604/compact_dex_converter_android_x86.zip)
> [compact_dex_converter_android_x86_64.zip](https://github.com/anestisb/vdexExtractor/files/2351605/compact_dex_converter_android_x86_64.zip)
> [compact_dex_converter_linux.zip](https://github.com/anestisb/vdexExtractor/files/2351606/compact_dex_converter_linux.zip)
> 
> Adb Instruction updated, thanks to @anestisb
> Added info for windows 10 users

cannot deodex with your tools bro
