### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by Furniel** [anestisb/vdexExtractor#26]
Got segmentation fault on SecFactoryPhoneTest.vdex(vdex 0.10 from Samsung galaxy note 9, android 8.1 rom)
```
[INFO] Processing 1 file(s) from SecFactoryPhoneTest.vdex
[DEBUG] [2836] 2018/08/30 19:44:12 (vdexExtractor.c:194 main) Processing 'SecFactoryPhoneTest.vdex'
[DEBUG] [2836] 2018/08/30 19:44:12 (vdex_api.c:41 vdexApi_initEnv) Initializing environment for Vdex version '010'
------ Vdex Header Info ------
magic header & version      : vdex-010
number of dex files         : 1 (1)
dex size (overall)          : 9d28 (40232)
verifier dependencies size  : 2b8 (696)
verifier dependencies offset: 9d44 (40260)
quickening info size        : 4 (4)
quickening info offset      : 9ffc (40956)
dex files info              :
  [0] location checksum : 1d2ba12a (489398570)
---- EOF Vdex Header Info ----
[DEBUG] [2836] 2018/08/30 19:44:12 (vdex/vdex_010.c:75 vdex_010_GetNextDexFileData) Processing first Dex file at offset:0x1c
[DEBUG] [2836] 2018/08/30 19:44:12 (dex.c:351 dex_isValidDex) Dex version '037' detected
Segmentation fault (core dumped)
```
[SecFactoryPhoneTest.zip](https://github.com/anestisb/vdexExtractor/files/2337121/SecFactoryPhoneTest.zip)

**Comment by bursoft-git** [comment]
it seems that everything is fine

C:\BatchApkTool\bin\bin64>vdexExtractor.exe -i SecFactoryPhoneTest.vdex
[INFO] Processing 1 file(s) from SecFactoryPhoneTest.vdex
[INFO] 1 out of 1 Vdex files have been processed
[INFO] 1 Dex files have been extracted in total
[INFO] Extracted Dex files are available in '.'

**Comment by anestisb** [comment]
Thanks for reporting. Fixed in https://github.com/anestisb/vdexExtractor/commit/957d12054196e255bb97c93ba0c8fc0099dc5d60.

**Comment by anestisb** [comment]
@bursoft-git depending on the memory layout the bug might not always trigger a crash (check commit description for more info).
