### ISSUE TITLE
Problem with .vdex Poco F1 (Xiaomi)

### ISSUE THREAD

**Issue by ale8530** [anestisb/vdexExtractor#37]
I have of the problems with these files:

[Files.zip](https://github.com/anestisb/vdexExtractor/files/2383016/Files.zip)

Is possible fix this problem?

Thanks

**Comment by anestisb** [comment]
What is the problem? I don't see any issues when decompiling/disassembling the files you've provided. Also be aware that the Vdex containers you've provided are of version 010 (probably from an Oreo ROM).

**Comment by ale8530** [comment]
Yes is oreo 8.1 the problem is lastversion vdex 0.52? i try with old version?

**Comment by anestisb** [comment]
I've tested against the current master. You should be ok with the latest version. What is exactly the error you get?

**Comment by ale8530** [comment]
Sorry is problem of my script because these apk has classes.dex and classes2.dex

I have fixed.

Sorry for disturb

Thanks for your reply
