### ISSUE TITLE
小米8se的8.9.13开发版刷机包中framework中的services.vdex转换失败

### ISSUE THREAD

**Issue by lihai1913** [anestisb/vdexExtractor#39]
` unverified classes: number_of_classes=14
  0000: 'Landroid/hardware/vibrator/V1_0/Constants$Effect;' is expected to be verified at runtime
  0001: 'Landroid/hardware/vibrator/V1_0/Constants$EffectStrength;' is expected to be verified at runtime
  0002: 'Landroid/hardware/vibrator/V1_0/Constants;' is expected to be verified at runtime
  0003: 'Landroid/hidl/base/V1_0/DebugInfo$Architecture;' is expected to be verified at runtime
  0004: 'Landroid/hidl/base/V1_0/DebugInfo;' is expected to be verified at runtime
  0005: 'Landroid/hidl/base/V1_0/IBase$Proxy;' is expected to be verified at runtime
  0006: 'Landroid/hidl/base/V1_0/IBase$Stub;' is expected to be verified at runtime
  0007: 'Landroid/hidl/base/V1_0/IBase;' is expected to be verified at runtime
  0008: 'Landroid/net/INetd$Stub$Proxy;' is expected to be verified at runtime
  0009: 'Landroid/net/INetd$Stub;' is expected to be verified at runtime
  0010: 'Landroid/net/INetd;' is expected to be verified at runtime
  0011: 'Landroid/os/IInstalld$Stub$Proxy;' is expected to be verified at runtime
  0012: 'Landroid/os/IInstalld$Stub;' is expected to be verified at runtime
  0013: 'Landroid/os/IInstalld;' is expected to be verified at runtime
----- EOF Vdex Deps Info -----
[ERROR] Unexpected checksum (38206974 vs b4756bdf) - failed to unquicken Dex file
[ERROR] Failed to process Dex files - skipping '/tmp/services.vdex'
[INFO] 0 out of 1 Vdex files have been processed
[INFO] 0 Dex files have been extracted in total
[INFO] Extracted Dex files are available in '/tmp'
`
附下载地址：https://pan.baidu.com/s/1XlRsImJacd6vlx3Ra6sn-Q

**Comment by anestisb** [comment]
Can you please replace the chinese bits with English so I can understand what your issue is?
