### ISSUE TITLE
support for oat/art files

### ISSUE THREAD

**Issue by Cloud-stift** [anestisb/vdexExtractor#4]
how to use for these files like boot.art/boot.oat/boot.vdex.

**Comment by anestisb** [comment]
Android's runtime (ART) is using the OAT and ART files along with the VDEX as part of the bytecode execution engine. You can Google around the mechanics of the ART components. A brief overview of this information is available [here](https://census-labs.com/news/2015/06/18/fuzzing-objects-de-ART-HITB2015AMS/).

Supporting these files for any purposes is outside the scope of this project. You can find other utilities that can process them (e.g. oatdump).
