### ISSUE TITLE
If Possible - Prebuilt Binaries?

### ISSUE THREAD

**Issue by 0pLuS0** [anestisb/vdexExtractor#41]
Hello,

I know a lot of people in Android want to Deodex and patch their ROMs for Signature Spoofing to do microG on, and just running the cmds to accomplish this as it relates to getting you there with vdexExtractor are simple. 

The hard part for these newbies is compiling in Windows who have no clue.

So I understand all the differences on systems, libs, dependencies etc., I compile in Linux all the time.

If possible for you and you have the time, I know the Newbie Community out there would appreciate some Windows Binaries...

Thank for your consideration...

**Comment by anestisb** [comment]
Sorry I'll not distribute any precompiled binaries of the tool for any platform. It's a total nightmare to provide support for all these binaries across systems (e.g. my system libs are there and not there, the linker is complaining), plus I hate binary distribution for these type of simple OSS tools. I've already made some compromises with the Compact Dex Converter binaries, although I don't intend to do it for the main tool.

**Comment by 0pLuS0** [comment]
Ok, just thought I'd ask...
