### ISSUE TITLE
Can't extract vdex

### ISSUE THREAD

**Issue by 4lMaghraby** [anestisb/vdexExtractor#44]
I want to extract vdex of the settings app (odex+vdex) in order to completely decompile it
here is the link with boot.vdex and the settings app folder https://drive.google.com/open?id=1ycfsnYk9KsuNGyEYXQzKdYzFqSERQXBz
thanks in advance

**Comment by Furniel** [comment]
This vdex file has no dex data, open settings.apk and you will find original dex file there.

**Comment by 4lMaghraby** [comment]
thanks for the reply
I tried to do that but the apk can't be opened
would you help me with decompiling?

**Comment by anestisb** [comment]
As @Furniel mentioned the Vdex container does not contain any Dex data (used as a simple reference file from ART).

```
vdexExtractor -i Settings.vdex -o . -v 4
[INFO] Processing 1 file(s) from Settings.vdex
[DEBUG] [992] 2018/12/11 20:44:07 (vdexExtractor.c:222 main) Processing 'Settings.vdex'
[DEBUG] [992] 2018/12/11 20:44:07 (vdex_api.c:46 vdexApi_initEnv) Initializing environment for Vdex version '019'
------ Vdex Header Info -------
magic header                  : vdex
verifier dependencies version : 019
dex section version           : 000
number of dex files           : 1 (1)
verifier dependencies size    : 100d4 (65748)
verifier dependencies offset  : 18 (24)
quickening info size          : 0 (0)
quickening info offset        : ffffffff (4294967295)
---- EOF Vdex Header Info ----
[DEBUG] [992] 2018/12/11 20:44:07 (vdex/vdex_backend_019.c:406 vdex_backend_019_process) Vdex has no Dex data - skipping
[DEBUG] [992] 2018/12/11 20:44:07 (vdex/vdex_019.c:278 vdex_019_process) Took 0 ms to process Vdex file
[INFO] 1 out of 1 Vdex files have been processed
[INFO] 0 Dex files have been extracted in total
[INFO] Extracted Dex files are available in '.
```

In this case you can extract the Dex file from the APK (simply unzip it). Be aware that the one you provide in the link is corrupted (most likely an error happened when you downloaded from the device). Redownload it from the device and you should be ok.
