### ISSUE TITLE
android P. how to deodex system/framework?

### ISSUE THREAD

**Issue by Liberations** [anestisb/vdexExtractor#45]
I found boot-framework_classes.dex boot-framework_classes2.dex boot-framework_classes3.dex..
but how to get a full framework.jar ? please...

**Comment by anestisb** [comment]
Pull the boot-framework.jar from your device and append the extracted Dex file as zip entries (`jar -uf`). Be sure to maintain the naming conventions (classes.dex, classes2.dex, etc.).
