### ISSUE TITLE
Need to explain Android 9 deodex

### ISSUE THREAD

**Issue by sputnick-dev** [anestisb/vdexExtractor#47]
It's very confusing, not obvious what is the way to deodex Android 9.

Can you please send me a draft of the list of the commands to run ?

I will elaborate on this and create a pull request to have a clear doc with pleasure, or better a bash script. It's my job !

I try to deodex vdex files to enable signature spoofing to install MicroG via NanoDroid for LineageOS 16.0 alpha (Android 9.0 Pie SM-A520F device)

I follow instructions [from here](https://github.com/anestisb/vdexExtractor#compact-dex-converter)

I wonder how to use [vdexextractor/tools/deodex/run.sh](https://github.com/anestisb/vdexExtractor#compact-dex-converter"]vdexExtractor)

What I have tried so far : 

    adb shell
    $ find / -name '*.vdex' 2>/dev/null > /sdcard/list.vdex
    
    # from Linux
    $ adb pull /sdcard/list.vdex ~
    $ while read a; do
        mkdir -p ./${a%/*}
        adb pull "$a" ./$a
    done < ~/list.vdex
    $ find system
    system/system/framework/boot-android.test.base.vdex
    system/system/framework/arm64/boot-android.test.base.vdex
    system/system/framework/arm64/boot-ext.vdex
    system/system/framework/arm64/boot-telephony-common.vdex
    system/system/framework/arm64/boot-conscrypt.vdex
    system/system/framework/arm64/boot-android.hidl.base-V1.0-java.vdex
    system/system/framework/arm64/boot-framework-oahl-backward-compatibility.vdex
    system/system/framework/arm64/boot-okhttp.vdex
    system/system/framework/arm64/boot-bouncycastle.vdex
    system/system/framework/arm64/boot-android.hidl.manager-V1.0-java.vdex
    system/system/framework/arm64/boot-ims-common.vdex
    system/system/framework/arm64/boot-voip-common.vdex
    system/system/framework/arm64/boot.vdex
    system/system/framework/arm64/boot-core-libart.vdex
    system/system/framework/arm64/boot-apache-xml.vdex
    system/system/framework/arm64/boot-framework.vdex
    system/system/framework/boot-ext.vdex
    system/system/framework/boot-telephony-common.vdex
    system/system/framework/boot-conscrypt.vdex
    system/system/framework/boot-android.hidl.base-V1.0-java.vdex
    system/system/framework/boot-framework-oahl-backward-compatibility.vdex
    system/system/framework/boot-okhttp.vdex
    system/system/framework/boot-bouncycastle.vdex
    system/system/framework/oat/arm64/wifi-service.vdex
    system/system/framework/oat/arm64/com.android.location.provider.vdex
    system/system/framework/oat/arm64/org.lineageos.hardware.vdex
    system/system/framework/oat/arm64/org.lineageos.platform.vdex
    system/system/framework/oat/arm64/ethernet-service.vdex
    system/system/framework/oat/arm64/services.vdex
    system/system/framework/boot-android.hidl.manager-V1.0-java.vdex
    system/system/framework/boot-ims-common.vdex
    system/system/framework/boot-voip-common.vdex
    system/system/framework/boot.vdex
    system/system/framework/boot-core-libart.vdex
    system/system/framework/arm/boot-android.test.base.vdex
    system/system/framework/arm/boot-ext.vdex
    system/system/framework/arm/boot-telephony-common.vdex
    system/system/framework/arm/boot-conscrypt.vdex
    system/system/framework/arm/boot-android.hidl.base-V1.0-java.vdex
    system/system/framework/arm/boot-framework-oahl-backward-compatibility.vdex
    system/system/framework/arm/boot-okhttp.vdex
    system/system/framework/arm/boot-bouncycastle.vdex
    system/system/framework/arm/boot-android.hidl.manager-V1.0-java.vdex
    system/system/framework/arm/boot-ims-common.vdex
    system/system/framework/arm/boot-voip-common.vdex
    system/system/framework/arm/boot.vdex
    system/system/framework/arm/boot-core-libart.vdex
    system/system/framework/arm/boot-apache-xml.vdex
    system/system/framework/arm/boot-framework.vdex
    system/system/framework/boot-apache-xml.vdex
    system/system/framework/boot-framework.vdex
    
    $ cd /path/to/vdexExtractor
    $ find ../system -name '*.vdex' | while read a; do
         dir=${a%/*]
        tools/deodex/run.sh -i "$a" -o ../system_new
     done

But now, I have only as *.dex :
    
    system_new/framework/arm64/vdexExtractor_deodexed/boot-framework/boot-framework_classes3.dex
    system_new/framework/arm64/vdexExtractor_deodexed/boot-framework/boot-framework_classes2.dex
    system_new/framework/arm64/vdexExtractor_deodexed/boot-framework/boot-framework_classes.dex
    system_new/framework/vdexExtractor_deodexed/boot-framework/boot-framework_classes3.dex
    system_new/framework/vdexExtractor_deodexed/boot-framework/boot-framework_classes2.dex
    system_new/framework/vdexExtractor_deodexed/boot-framework/boot-framework_classes.dex
    system_new/framework/oat/arm64/vdexExtractor_deodexed/services/services_classes.dex
    system_new/framework/arm/vdexExtractor_deodexed/boot-framework/boot-framework_classes3.dex
    system_new/framework/arm/vdexExtractor_deodexed/boot-framework/boot-framework_classes2.dex
    system_new/framework/arm/vdexExtractor_deodexed/boot-framework/boot-framework_classes.dex

I think I miss something. 

 - I think I don't have one dex file per .vdex
 - the path is messy with vdexExtractor_deodexe extra dir
 - does I need to use instead bin/vdexExtractor binary ? The doc said to use 'compact_dex_extractor', but don't know how if not ran with tools/deodex/run.sh

I think I miss-use the tool.  What is the full list of commands to be able to patch Pie aka Android 9 ?

**Comment by anestisb** [comment]
I don't think you're messing up with anything. If the corresponding Dex files are successfully generated in means that the tool is doing its job. Its up to you then to manually repackage the Dex files back to Apks under the appropriate names and resign them.

And again as described in https://github.com/anestisb/vdexExtractor/issues/25#issuecomment-417369119, a full-stack deodexing is not among the primary purposes of this tool. However, I've noticed in the past that some folks have already wrapped around this tool their deodexing kits, so feel free to search for them in XDA forums or Google.

**Comment by palight** [comment]
I'm triying to deodex services.jar on Pie to install nanodroid-patcher and get signature spoofing, but after running script in tools/deodex/run.sh on it I obtain a folder named services_classes.dex with too files in it. Wich File I have to repack to services.jar ?

**Comment by anestisb** [comment]
@palight both files should be added back to the jar file following the naming convention (classes.dex, classes2.dex, etc.)

**Comment by palight** [comment]
Thanks you very much, I discovered it already, that was pretty obvious, but not vor neebies like me…

**Comment by Pavel87** [comment]
I am seriously struggling with extracting of telephony classes. Basically I have managed to retrieved system.img (Android P) and want to extract Telephony classes. I have a framework folder but struggling with extraction.

When running deodex:
Pav-MBP:deodex xxxuser$ ./run.sh -i ~/Desktop/framework
[INFO]: Processing 173 input Vdex files
[ERR ]: vdexExtractor execution failed
[ERROR] [84989] 2019/06/06 16:17:36 (utils.c:118 utils_init) Couldn't stat the input file/dir '/Users/xxxuser/Desktop/framework/arm/boot-framework.vdex': No such file or directory
[FATAL] [84989] 2019/06/06 16:17:36 (vdexExtractor.c:159 main) Couldn't load input files
Pav-MBP:deodex xxxuser$ 

Even this error shows and it creates bunch of dex files (i.e. /vdexExtractor_deodexed/boot-telephony-common/boot-telephony-common_classes.dex) dex2jar convertion doesn't work. 

Here is a link to the framework folder I am dealing with but maybe you know the answer without this
[https://drive.google.com/file/d/1iPPKK1s5N_JmXVKZtKJP-qqk74Gc7KVJ/view?usp=sharing](url)

Thanks in advance.
