### ISSUE TITLE
can download from live.com

### ISSUE THREAD

**Issue by chongbo2013** [anestisb/vdexExtractor#49]
can download from live.com?

**Comment by anestisb** [comment]
You mean onedrive locations are not working? Can you paste the error message to investigate?

**Comment by ybtag** [comment]
First run detected - downloading compact_dex_converter bin & lib dependencies
--2024-01-15 10:35:05--  https://onedrive.live.com/download?cid=D1FAC8CC6BE2C2B0&resid=D1FAC8CC6BE2C2B0%21581&authkey=AE_kzPqzG_-R4T0
Resolving onedrive.live.com (onedrive.live.com)... 13.107.139.11, 13.107.137.11
Connecting to onedrive.live.com (onedrive.live.com)|13.107.139.11|:443... connected.
HTTP request sent, awaiting response... 403 Forbidden
2024-01-15 10:35:05 ERROR 403: Forbidden.

dependencies download failed

However, when I open the link in my browser it downloads fine
