### ISSUE TITLE
Pixel2 services.vdex fails to unquicken dex

### ISSUE THREAD

**Issue by jtothe4n** [anestisb/vdexExtractor#5]
> [ERROR] Unexpected checksum (89f9fc35 vs fa7bb981) - failed to unquicken Dex file

using latest 0.4.0 this time :o)

[services.zip](https://github.com/anestisb/vdexExtractor/files/1597058/services.zip)

**Comment by anestisb** [comment]
Check https://github.com/anestisb/vdexExtractor/issues/3

I have a feeling it's the sam issue.

**Comment by jtothe4n** [comment]
Oh yeah, my bad (again) didn't check the issue tracker.
