### ISSUE TITLE
Unexpected checksum (7d70f08b vs 4ff0a59e) - failed to unquicken Dex file

### ISSUE THREAD

**Issue by addhaloka** [anestisb/vdexExtractor#50]
Sample download:
[app.zip](https://github.com/anestisb/vdexExtractor/files/3293333/app.zip)

I have to specify --ignore-crc-error in order to generate dex file, but the result dex looks corrupted.  

dex2oat output:
oat_writer.cc:3082] Failed to open dex file from oat file. File: app.apk Error: Failure to verify dex file 'app.apk': could not find declaring class for virtual method index 6634

**Comment by anestisb** [comment]
@addhaloka false alarm?
