### ISSUE TITLE
Deodexing Android Q support

### ISSUE THREAD

**Issue by ingbrzy** [anestisb/vdexExtractor#51]
There is an error when deodexing apk from Android Q..

`[ERROR] Unsupported Vdex version
[WARNING] Invalid Vdex header - skipping`

example Q apk
[Bluetooth_Q.zip](https://github.com/anestisb/vdexExtractor/files/3383237/Bluetooth_Q.zip)

**Comment by ingbrzy** [comment]
vdex version is vdex021

**Comment by IgorEisberg** [comment]
Some more examples with DEX section (same version 002) from a Pixel 3 XL ROM.
[https://www.mediafire.com/file/cdx1f4j621whxzt/crosshatch-qpp5.190530.014.zip/file](url)
Note: The good thing is that it seems most (all?) APKs and JARs on Android Q already have their original classes*.dex files, along with *.vdex files (most of them don't have a DEX section).

**Comment by mooseIre** [comment]
I had the same problem when I deal  MI9 AndroidQ .
Error:Unsupported Vdex version.vdex version is 021
but i can remove all oat except framework/arm &framework/arm64.

get rom:
http://hugeota.d.miui.com/9.7.11/miui_CEPHEUS_9.7.11_50e56ce0f7_10.0.zip

**Comment by IgorEisberg** [comment]
> I had the same problem when I deal MI9 AndroidQ .
> Error:Unsupported Vdex version.vdex version is 021
> but i can remove all oat except framework/arm &framework/arm64.
> 
> get rom:
> http://hugeota.d.miui.com/9.7.11/miui_CEPHEUS_9.7.11_50e56ce0f7_10.0.zip

Already made a solution for us ROM makers:
https://github.com/anestisb/vdexExtractor/pull/52

Although, it seems that APKs in Android Q ROMs all have their classes*.dex files already, but it's uncertain whether it will be the same with the final release of Android Q.

**Comment by mooseIre** [comment]
> solution

I had used it , but always fail .
it can not extract dex from 021vdex,
but it didn't show   'Unsupported Vdex version'

**Comment by IgorEisberg** [comment]
> > solution
> 
> I had used it , but always fail .
> it can not extract dex from 021vdex,
> but it didn't show 'Unsupported Vdex version'

Most vdex files on that ROM don't have a DEX section, means no dex files to extract.
The only vdex files with a DEX section in that ROM are:

> mab.vdex
> SogouInput.vdex
> SystemHelper.vdex
> UPTsmService.vdex
> WebViewGoogle.vdex

Try one of them.

**Comment by mooseIre** [comment]
> > > solution
> > 
> > 
> > I had used it , but always fail .
> > it can not extract dex from 021vdex,
> > but it didn't show 'Unsupported Vdex version'
> 
> Most vdex files on that ROM don't have a DEX section, means no dex files to extract.
> The only vdex files with a DEX section in that ROM are:
> 
> > mab.vdex
> > SogouInput.vdex
> > SystemHelper.vdex
> > UPTsmService.vdex
> > WebViewGoogle.vdex
> 
> Try one of them.

thanks ，I get it.

**Comment by anestisb** [comment]
Hopefully will start working Android 10 support this weekend.

**Comment by vagyula1** [comment]
Any news?

**Comment by anestisb** [comment]
Android 10 support implemented.

**Comment by mooseIre** [comment]
thanks

**Comment by shuidixu** [comment]
Hi

It looks like your tool doesn't work on Android 10 with Samsung

```
[WARN]: Skipping 'vsimmanager' since no decompiled resources found
[WARN]: Skipping 'wifi-service' since no decompiled resources found
[INFO]: 0 binaries have been successfully deodexed
```
do you have any idea why it happened? Or how to fix this?

**Comment by anestisb** [comment]
@shuidixu  please raise a different issue and share app samples if you have issues with the tool.

**Comment by codingpoem** [comment]
[WARN]: Skipping 'boot-okhttp' since no decompiled resources found
[WARN]: Skipping 'boot-framework' since no decompiled resources found

please help me to analyse the warn

get vdex: 
https://hifun.lanzous.com/iM7kDh1renc
