### ISSUE TITLE
[ERROR] Unsupported Vdex version  - [WARNING] Invalid Vdex header 

### ISSUE THREAD

**Issue by antipiot** [anestisb/vdexExtractor#53]
Hello Everybody!

I'm trying to get the cdex files from my boot-framework.vdex file but i run into thoses error:
I did look on other posts to try to figure out what was wrong by myself without luck:
tried on master and 0.5.2 with no luck: same error:

Vdex are from Android 9 Onplus 6 Rom

`root@omv-labo:~/vdexExtractor# /root/vdexExtractor/bin/vdexExtractor -i "/root/boot-framework.vdex" -o "/root/extracted" --log-file=/root/log.txt
[INFO] Processing 1 file(s) from /root/boot-framework.vdex
[ERROR] Unsupported Vdex version
[WARNING] Invalid Vdex header - skipping '/root/boot-framework.vdex'
[INFO] 0 out of 0 Vdex files have been processed
[INFO] 0 Dex files have been extracted in total
[INFO] Extracted Dex files are available in '/root/extracted'
`

Log file is empty.

Am i doing something wrong?

Thanks for your help!

**Comment by anestisb** [comment]
Can you please enable verbose mode in output and attach/share the vdex somewhere for me to inspect?
