### ISSUE TITLE
Is compact_dex_converter output differrent dex version like dex.038/dex.039 possible?

### ISSUE THREAD

**Issue by zzzzfeng** [anestisb/vdexExtractor#54]
thanks for this tool first!
Cause default output dex.039 is not supported by androguard, Is 'compact_dex_converter' output differrent dex version like dex.038/dex.039 possible?

**Comment by anestisb** [comment]
No that is not possible by this tool (or any tool). Dex039 has instructions that are not available in dex038 and there is no straight forward way to create equivalent code. Unfortunately you need to find a different tool for what you're looking for in androguard (or contribute to it with new version support).
