### ISSUE TITLE
Help Needed Compiling Windows vdexExtractor

### ISSUE THREAD

**Issue by Ticklefish** [anestisb/vdexExtractor#59]
Hi, I have to admit this isn't really an issue - it's a request. 

Actually it's a begging request and I'm a little embarrassed to do it but I'm out of options.

Is anybody able to share a Windows compatible version of the latest build of vdexExtractor? This tool is invaluable for deodexing and I am very keen to update my version...but I only have access to the PC at work and can't install the necessary programmes to build it myself..
I've tried looking for ways around the restrictions on my computer but without any luck. To be honest, I'd rather not do anything too drastic in case I kinda like having a job.

So apologies for asking but...can anybody help?

**Comment by anestisb** [comment]
Just google how to compile under cygwin and you will get your answer.

**Comment by Ticklefish** [comment]
Thanks for your reply. I can't install cygwin, as I mentioned previously, so I guess I'm out of luck.
