### ISSUE TITLE
does't work for android 10

### ISSUE THREAD

**Issue by icew4y** [anestisb/vdexExtractor#60]
`./bin/vdexExtractor -i /mnt/d/Project/newxiaomi/system/framework/oat/arm64/services.vdex`
`[INFO] Processing 1 file(s) from /mnt/d/Project/newxiaomi/system/framework/oat/arm64/services.vdex

[INFO] 1 out of 1 Vdex files have been processed

[INFO] 0 Dex files have been extracted in total

[INFO] Extracted Dex files are available in '/mnt/d/Project/newxiaomi/system/framework/oat/arm64'`

[services.zip](https://github.com/anestisb/vdexExtractor/files/4241219/services.zip)

**Comment by icew4y** [comment]
looks like this vdex file do not have dex section.

**Comment by zhousysu** [comment]
I also have this problem in MIUI

**Comment by icew4y** [comment]
> I also have this problem in MIUI

solved by using superr-kitchen

**Comment by zhousysu** [comment]
> > I also have this problem in MIUI
> 
> solved by using superr-kitchen

are you using superr-kitchen to decompline boot.img of MIUI ROM ?

**Comment by icew4y** [comment]
> > > I also have this problem in MIUI
> > 
> > 
> > solved by using superr-kitchen
> 
> are you using superr-kitchen to decompline boot.img of MIUI ROM ?

yes

**Comment by zhousysu** [comment]
> > > > I also have this problem in MIUI
> > > 
> > > 
> > > solved by using superr-kitchen
> > 
> > 
> > are you using superr-kitchen to decompline boot.img of MIUI ROM ?
> 
> yes


emmmm, but huawei rom can not download from the offical website.
this way is not general
