### ISSUE TITLE
vdexExtractor cannot use in Android 10，can you help me？

### ISSUE THREAD

**Issue by tjzhou23** [anestisb/vdexExtractor#61]
Hello, thank you very much for developing such a great tool, vdexExtractor.
However, I recently discovered that , I am using "adb pull /system/framework/*.dex", and then using vdexExtractor can't get the dex file on Android 10. The boot-framework.vdex are small on Android 10, but the boot-framework.oat and boot-framework.art files are big, it is strange. 
In addition, I cannot use jadx to open the /system/framework/framework.jar file directly. 
The framework.jar contains 4 dex files. Decompressing the framework.jar to export the dex, I also cannot use jadx to view the dex source code.it makes me upset.
can you help me solve this problem?

**Comment by zhousysu** [comment]
the rom http://bigota.d.miui.com/V11.0.5.0.QFACNXM/miui_CEPHEUS_V11.0.5.0.QFACNXM_035a571448_10.0.zip

**Comment by jiajunpei** [comment]
May be there's no dex file in vdex file ?
Android 9 introduced uncompressed dex,  and for Android 10, most of the boot dex files are not compressed in the jar files.
For such kind of jars, dex2oat will not re-write dex file to vdex files.

**Comment by BruteKoon** [comment]
in my case, the same problem.
android 8, the vdex_extractor operates well.
but Android 9~10 this vdex_extracotr is not doing well!

always this log print
ERROR] Unsupported Vdex version
[WARNING] Invalid Vdex header - skipping './Pixel/framework/arm64/boot-ims-common.oat'

**Comment by shuidixu** [comment]
i also can't run it on Android 10,
can you help?

**Comment by zixing131** [comment]
me too
