### ISSUE TITLE
The GCC compiler tells me that the program compilation error: multiple definition

### ISSUE THREAD

**Issue by gesangtome** [anestisb/vdexExtractor#66]
When using the GCC compiler to build this program, gcc told me that there are multiple definitions in 'vdex/vdex_backend_019.o', This is a patch I made, it can solve the problem, I am not sure if it is perfect enough?
Find it here: https://github.com/anestisb/vdexExtractor/pull/65

This is the GCC I am using:
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/libexec/gcc/x86_64-redhat-linux/10/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-redhat-linux
Configured with: ../configure --enable-bootstrap --enable-languages=c,c++,fortran,objc,obj-c++,ada,go,d,lto --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-shared --enable-threads=posix --enable-checking=release --enable-multilib --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-linker-build-id --with-gcc-major-version-only --with-linker-hash-style=gnu --enable-plugin --enable-initfini-array --with-isl --enable-offload-targets=nvptx-none --without-cuda-driver --enable-gnu-indirect-function --enable-cet --with-tune=generic --with-arch_32=i686 --build=x86_64-redhat-linux
Thread model: posix
Supported LTO compression algorithms: zlib zstd
gcc version 10.0.1 20200430 (Red Hat 10.0.1-0.14) (GCC)

**Comment by anestisb** [comment]
Does the work. Weird how I didn't come across it when testing with older GCC versions. Thank you for reporting and fixing the issue.
