### ISSUE TITLE
Problem with SmsExtra.apk

### ISSUE THREAD

**Issue by ale8530** [anestisb/vdexExtractor#7]
Meanwhile, thank you again for the tool, but I found an error with this file, you can view it? :)
[SmsExtra.zip](https://github.com/anestisb/vdexExtractor/files/1625329/SmsExtra.zip)

**Comment by Variusis** [comment]
I support this problem takes place

**Comment by anestisb** [comment]
Thanks for reporting it. Will check it out.

**Comment by ale8530** [comment]
News ? :)

**Comment by anestisb** [comment]
Unfortunately was really busy. I'll probably start working on it by the weekend or early next week.

**Comment by ale8530** [comment]
Thank you for your kindness in answering, take the time it takes, I just wanted to know if there were any news :)

**Comment by anestisb** [comment]
If you use the 0.3.1 version it is successfully decompiled. So it seems that the Dex instruction backend logic that has been added to support Vdex version 010 is creating the problem. Will try to fix it today.

**Comment by ale8530** [comment]
thank you very much for your fix

**Comment by anestisb** [comment]
Should be fixed in master branch too.

**Comment by ale8530** [comment]
I have tested and created the SmsExtra_classes.dex file, but when you do this command, many errors occur on the terminal

Try this command:

./vdexExtractor -i SmsExtra.vdex

**Comment by anestisb** [comment]
Can you pull the latest master and try again please? An invalid free() bug was introduced in the recent recursion feature.

**Comment by ale8530** [comment]
https://pastebin.com/sddL62WG error

**Comment by ale8530** [comment]
If I cast ./vdexExtractor -h it is still 0.40 you should correct version number, but I checked if I was not aligned but I'm up to the last commit ;)

**Comment by anestisb** [comment]
Yeah I haven't bumped the version yet since I want to run some more tests before tag. If you run git log inside your clone the last commit should be the https://github.com/anestisb/vdexExtractor/commit/c83d738be6962200374ee4fb306f04f1d179edb7.

Can you double check please and if the bug is still there try compiling with debug symbols (`DEBUG=true ./make.sh`) so we can get more info from the stack trace.

**Comment by ale8530** [comment]
Now perfect very thanks
