### ISSUE TITLE
Problem with wifi-service.jar and services.jar android 8.1

### ISSUE THREAD

**Issue by ale8530** [anestisb/vdexExtractor#9]
There are some problems in deodexing these files:

[service.zip](https://github.com/anestisb/vdexExtractor/files/1741169/service.zip)
[wifi-service.zip](https://github.com/anestisb/vdexExtractor/files/1741170/wifi-service.zip)

**Comment by anestisb** [comment]
Duplicate of https://github.com/anestisb/vdexExtractor/issues/3

**Comment by ale8530** [comment]
you are right, sorry :)
